### ISSUE TITLE
Add .idea folder to .gitignore of first alda assignment 'simpletime'

### ISSUE THREAD

**Issue by Jan-GJ** [FontysVenlo/alda_simpletime_api#1]
**Is your feature request related to a problem? Please describe.**
The problem is that files created by using the Intelij IDEA are not excluded by the .gitignore. These files can be found in the .idea folder and are local IDE settings etc... .

**Describe the solution you'd like**
Add a .idea entry to the .gitignore.

**Describe alternatives you've considered**
Not staging files in the .idea folder.

**Additional context**
None

**Comment by Bonajo** [comment]
Done in the new assignment.
Thanks for the feedback :)
